export const categories = [
"Auto, Boat & Air", 
"Business & Professional",
"Charity & Causes",
"Community & Culture",
"Family & Education",
"Fashion & Beauty",
"Film",
"Media & Entertainment",
"Food & Drink",
"Goverment & Politics",
"Health & Wellness",
"Hobbies & Special Interest",
"Home & Lifestyle",
"Music",
"Other",
"Performing & Visual Arts",
"Religion & Spirituality",
"Science & Technology",
"Seasonal & Holiday",
"Sports & Fitness",
"Travel & Outdoor" ];
